In [2]:
import numpy as np
import pandas as pd

In [ ]:
# 1

In [147]:
my_array = np.arange(0,100,5)
my_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
# 2

In [148]:
my_array = my_array[::2]
my_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# 3

In [149]:
my_array = my_array.reshape(5,2)
my_array

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [ ]:
# 4

In [150]:
my_second_array = my_array.copy()
my_second_array -= 5
my_second_array

array([[-5,  5],
       [15, 25],
       [35, 45],
       [55, 65],
       [75, 85]])

In [ ]:
# 5

In [163]:
sum = np.hstack((my_second_array,my_array))
sum = sum.T
sum

array([[-5, 15, 35, 55, 75],
       [ 5, 25, 45, 65, 85],
       [ 0, 20, 40, 60, 80],
       [10, 30, 50, 70, 90]])

In [ ]:
# 6

In [167]:
# my_array = my_array.T
# my_second_array = my_second_array.T
result = sum[1]/my_array[1]
result2 = sum[2]/my_second_array[1]
result

array([0.5       , 0.83333333, 0.9       , 0.92857143, 0.94444444])

In [166]:
result2

array([0.        , 0.8       , 0.88888889, 0.92307692, 0.94117647])

In [ ]:
# 7

In [ ]:
# 8

In [171]:
some_array = sum.copy()
some_array[[0,2]] = some_array[[2,0]]
some_array

array([[ 0, 20, 40, 60, 80],
       [ 5, 25, 45, 65, 85],
       [-5, 15, 35, 55, 75],
       [10, 30, 50, 70, 90]])

In [ ]:
# 9

In [174]:
for i in sum:
    print(f"Среднее значение: {np.mean(i)}")
    print(f"Медиана: {np.median(i)}")
    print(f"Стандартное отклонение {np.std(i)}")

Среднее значение: 35.0
Медиана: 35.0
Стандартное отклонение 28.284271247461902
Среднее значение: 45.0
Медиана: 45.0
Стандартное отклонение 28.284271247461902
Среднее значение: 40.0
Медиана: 40.0
Стандартное отклонение 28.284271247461902
Среднее значение: 50.0
Медиана: 50.0
Стандартное отклонение 28.284271247461902


In [ ]:
# 10

In [175]:
for i in sum:
    for j in i:
        print(j/i.max())

-0.06666666666666667
0.2
0.4666666666666667
0.7333333333333333
1.0
0.058823529411764705
0.29411764705882354
0.5294117647058824
0.7647058823529411
1.0
0.0
0.25
0.5
0.75
1.0
0.1111111111111111
0.3333333333333333
0.5555555555555556
0.7777777777777778
1.0


## second tasks

In [4]:
df = pd.read_csv('C:\\Users\\user\Desktop\BigData\Global Population Trends(2016-2022).csv')
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

In [90]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [91]:
df.shape

(1073, 12)

In [92]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [93]:
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

In [5]:
df1=df[df['Total Population']!='-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

In [6]:
# Преобразование типа столбца 'Total Population'
df1['Total Population'] = df1['Total Population'].str.replace(',', '', regex=True).astype(int)
print(df1.dtypes)

Country                   object
Year                       int64
Total Population           int32
Urban Population          object
Rural Population          object
Population Density        object
Life Expectancy           object
Birth Rate               float64
Death Rate               float64
Fertility Rate            object
Infant Mortality Rate     object
Growth Rate               object
dtype: object


C:\Users\user\AppData\Local\Temp\ipykernel_11792\948466797.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Total Population'] = df1['Total Population'].str.replace(',', '', regex=True).astype(int)


In [190]:
df1.max()

Country                    Zimbabwe
Year                           2021
Total Population         1412360000
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object

In [187]:
df1.min()

Country                  Afghanistan
Year                            2018
Total Population               10865
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                     -1.0
dtype: object

In [97]:
df1.describe()

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

In [127]:
df1.sort_values(['Country', 'Life Expectancy'])

Country  Year Total Population Urban Population Rural Population  \
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
...           ...   ...              ...              ...              ...   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
4                     -            62.0      35.842       7.344   
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
3                    60            63.0      36.051       7.113   
2                    58            64.0      36.466       6.791   
...                 ...             ...         ...         ...   
1072                  -            59.0      30.537       9.057   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   

     Fertility Rate Infant Mortality Rate Growth Rate  
4             4.643                  43.4         3.0  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
3              4.75                  44.8         3.0  
2              4.87                  46.3         3.0  
...             ...                   ...         ...  
1072          3.491                  35.7         2.0  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  

[1073 rows x 12 columns]

In [7]:
# индекс строки с максимальным значением численности населения
max_population_index = df1['Total Population'].idxmax()
min_population_index = df1['Total Population'].idxmin()
# название страны с максимальной численностью населения
country_with_max_population = df1.loc[max_population_index, 'Country']
country_with_min_population = df1.loc[min_population_index, 'Country']
print(f"Страна с максимальной численностью населения: {country_with_max_population}")
print(f"Страна с минимальной численностью населения: {country_with_min_population}")

Страна с максимальной численностью населения: China
Страна с минимальной численностью населения: Tuvalu


In [136]:
# 2.11

In [195]:
df.to_excel(r'C:\\Users\\user\Downloads\Global Population Trends(2016-2022).xlsx')